version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0

    steps:
      - checkout

      # Restaurar caché de dependencias de Maven
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      # Descargar dependencias
      - run:
          name: Descargar dependencias
          command: mvn dependency:go-offline

      # Guardar caché de dependencias
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # Ejecutar pruebas
      - run:
          name: Ejecutar pruebas
          command: mvn test

      # Guardar reportes de pruebas como artefactos
      - store_artifacts:
          path: target/cucumber-reports
          destination: cucumber-reports

workflows:
  version: 2
  build-test-workflow:
    jobs:
      - build-and-test